export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED";
export const LOGIN_USER_SUCCEEDED = "LOGIN_USER_SUCCEEDED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER_REQUESTED = "LOGOUT_USER_REQUESTED";
export const LOGOUT_USER_SUCCEEDED = "LOGOUT_USER_SUCCEEDED";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

export const REGISTER_USER_REQUESTED = "REGISTER_USER_REQUESTED";
export const REGISTER_USER_SUCCEEDED = "REGISTER_USER_SUCCEEDED";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
