export const GET_ALL_POSTS_REQUESTED = "GET_ALL_POSTS_REQUESTED";
export const GET_ALL_POSTS_SUCCEEDED = "GET_ALL_POSTS_SUCCEEDED";
export const GET_ALL_POSTS_FAILED = "GET_ALL_POSTS_FAILED";

export const GET_LIKED_POSTS_REQUESTED = "GET_LIKED_POSTS_REQUESTED";
export const GET_LIKED_POSTS_SUCCEEDED = "GET_LIKED_POSTS_SUCCEEDED";
export const GET_LIKED_POSTS_FAILED = "GET_LIKED_POSTS_FAILED";

export const GET_USER_POSTS_REQUESTED = "GET_USER_POSTS_REQUESTED";
export const GET_USER_POSTS_SUCCEEDED = "GET_USER_POSTS_SUCCEEDED";
export const GET_USER_POSTS_FAILED = "GET_USER_POSTS_FAILED";

export const LIKE_POST_REQUESTED = "LIKE_POST_REQUESTED";
export const LIKE_POST_SUCCEEDED = "LIKE_POST_SUCCEEDED";
export const LIKE_POST_FAILED = "LIKE_POST_FAILED";

export const UNLIKE_POST_REQUESTED = "UNLIKE_POST_REQUESTED";
export const UNLIKE_POST_SUCCEEDED = "UNLIKE_POST_SUCCEEDED";
export const UNLIKE_POST_FAILED = "UNLIKE_POST_FAILED";
